version: '3.8'

services:
  webapp:
    build:
      context: .
    container_name: webapp
    ports:
      - "5000:5000"
    volumes:
      - /var/log/webapp:/var/log/webapp
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
    networks:
      - monitoring

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expenses_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: reallystrongpassword
    ports:
      - "3306:3306"
    networks:
      - monitoring
    volumes:
      - mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mysql-data:
  grafana-data:

networks:
  monitoring:
