global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['webapp:5000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']