name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t flask-app:${{ github.sha }} .
          docker save flask-app:${{ github.sha }} > flask-app.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flask-app-image
          path: flask-app.tar
