name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run API Tests
        run: |
          source venv/bin/activate
          pytest test_api.py --maxfail=1 --disable-warnings

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: executing remote ssh commands using password  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USER }}  
          key: ${{ secrets.EC2_KEY }} 
          script: |
            sudo docker stop webapp || true
            sudo docker rm webapp || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
            sudo docker run -d --name webapp -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
