name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: flask-app-image:latest
          outputs: type=docker,dest=/tmp/flask-app-image.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-app-image
          path: /tmp/flask-app-image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:latest

      - name: executing remote ssh commands using password  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USER }}  
          key: ${{ secrets.EC2_KEY }} 
          port: 22
          script: |
            cd expenses-app
            sudo systemctl start docker
            sudo docker stop webapp || true
            sudo docker rm webapp || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
            sudo docker run -d --name webapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
