name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: flask-app-image:latest
          outputs: type=docker,dest=/tmp/flask-app-image.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-app-image
          path: /tmp/flask-app-image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: flask-app-image
          path: /tmp
      
      - name: Start and verify Docker service
        run: |
          sudo service docker start
          sudo docker info

      - name: Load Docker image
        run: |
          sudo docker load --input /tmp/flask-app-image.tar

      - name: Deploy to AWS EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
        run: |
         ssh -o StrictHostKeyChecking=no ec2-user@${{ env.INSTANCE_IP }} \
          "docker run -d -p 80:5000 flask-app:${{ github.sha }}"
