name: Deploy to AWS EC2

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: flask-app-image
          path: flask-app.tar

      - name: Load Docker Image
        run: docker load < flask-app.tar

      - name: Deploy to AWS EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.INSTANCE_IP }} \
          "docker run -d -p 80:5000 flask-app:${{ github.sha }}"
